# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Expose ports to the host.
  config.vm.network "forwarded_port", guest: 4646, host: 4646, host_ip: "127.0.0.1"    # Nomad
  config.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "127.0.0.1"    # Consul UI
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"    # Nomad Autoscaler health check
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"    # Demo webapp
  config.vm.network "forwarded_port", guest: 1936, host: 1936, host_ip: "127.0.0.1"    # HAProxy stats
  config.vm.network "forwarded_port", guest: 9090, host: 9090, host_ip: "127.0.0.1"    # Prometheus
  config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"    # Grafana

  # VM configuration.
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Provision demo dependencies.
  #   - Downloads and install Nomad, Consul and Docker
  # Only runs when the VM is created.
  config.vm.provision "deps", type: "shell", inline: <<-SHELL

    mkdir /tmp/downloads

    # Install dependencies.
    apt-get update
    apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      jq \
      software-properties-common \
      zip

    # Download and install Docker.
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

    apt-get update
    apt-get install -y \
      consul \
      nomad \
      docker-ce \
      docker-ce-cli \
      containerd.io
    usermod -aG docker vagrant

    pushd /tmp/downloads

#    # Download and install Hey.
#    wget --quiet https://storage.googleapis.com/hey-release/hey_linux_amd64
#    mv hey_linux_amd64 /usr/local/bin/hey
#    chmod +x /usr/local/bin/hey

    # build Hey
    wget https://github.com/rakyll/hey/archive/v0.1.4.zip
    unzip -qq v0.1.4.zip
    cd hey-0.1.4
    docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:latest go build -o ./bin/hey_linux_amd64
    cp bin/hey_linux_amd64 /usr/local/bin/hey
    docker image rm golang:latest
    cd ..

    # Download and install source files
    wget --quiet https://github.com/hashicorp/nomad-autoscaler/archive/v0.1.1.zip
    unzip -qq v0.1.1.zip
    pushd nomad-autoscaler-0.1.1/demo/vagrant
    mkdir /home/vagrant/nomad-autoscaler/
    mv files /home/vagrant/nomad-autoscaler/
    mv jobs /home/vagrant/nomad-autoscaler/
    chown -R vagrant:vagrant /home/vagrant/nomad-autoscaler/
    popd

    popd
    rm -fr /tmp/downloads
  SHELL

  # Setup demo dependencies.
  #   - Create daemons for Nomad and Consul
  # Runs everytime the VM starts.
  config.vm.provision "app:setup", type: "shell", run: "always", inline: <<-SHELL
    # create paths for Nomad host volumes
    mkdir -p /opt/nomad-volumes
    pushd /opt/nomad-volumes
    mkdir -p grafana
    chown 472:472 grafana
    popd

    # configure Nomad and Consul daemons
    pushd /home/vagrant/nomad-autoscaler/files
    for t in consul nomad; do
      cp ${t}.hcl /etc/${t}.d/
      systemctl enable $t
      systemctl start $t
    done
    popd
  SHELL

end
